### ISSUE TITLE
you can't access the mods menu if the folder doesn't exist or if it doesn't contain any sub-folders

### ISSUE THREAD

**Issue by giganlak** [giganlak/wood#233]
Instead of opening these menus 
![image](https://user-images.githubusercontent.com/72966048/181668521-37ccdfff-2806-47dd-be39-8d9f1fae62f4.png)

This happens:
![image](https://user-images.githubusercontent.com/72966048/181693867-3c8311ea-f27c-40be-8fb9-21c2ad684b37.png)

**Comment by ConaII** [comment]
Issue fixed in [2.0snap1-b2]( https://github.com/giganlak/wood/releases/tag/2.0snap1-b2 )
