### ISSUE TITLE
in the achievement resetting menu, the index number of the achievements in the list of achievements you can reset increases wrongly

### ISSUE THREAD

**Issue by giganlak** [giganlak/wood#239]
![image](https://user-images.githubusercontent.com/79335163/182045364-0b63f5cb-ba5c-4efb-bc1c-34b1e4de0240.png)

**Comment by ConaII** [comment]
Issue fixed in [2.0snap1-b2]( https://github.com/giganlak/wood/releases/tag/2.0snap1-b2 )
