### ISSUE TITLE
if you use the go back option in the game settings menu, it closes all menus and takes you back to the game instead of taking you to the settings menu

### ISSUE THREAD

**Issue by giganlak** [giganlak/wood#240]
![image](https://user-images.githubusercontent.com/79335163/182045488-41c37113-4de9-477a-9462-ac4873ec0e0f.png)

**Comment by ConaII** [comment]
Issue fixed in [2.0snap1-b2]( https://github.com/giganlak/wood/releases/tag/2.0snap1-b2 )
