### ISSUE TITLE
the message that appears when you eat an orange says "You eat a orange" instead of saying "You eat an orange"

### ISSUE THREAD

**Issue by giganlak** [giganlak/wood#293]
![image](https://user-images.githubusercontent.com/79335163/185527039-e1d3b66d-393a-4db9-9e7e-cd4a72fb4859.png)

**Comment by ConaII** [comment]
Issue fixed in [2.0snap1-b4]( https://github.com/giganlak/wood/releases/tag/2.0snap1-b4 )
