### ISSUE TITLE
the message that appears when you eat an apple says "You eat a apple" instead of saying "You eat an apple"

### ISSUE THREAD

**Issue by giganlak** [giganlak/wood#294]
![image](https://user-images.githubusercontent.com/79335163/185527135-85d76ab5-4e37-4bd5-9cd3-ccd506a38c1d.png)

**Comment by ConaII** [comment]
Issue fixed in [2.0snap1-b4]( https://github.com/giganlak/wood/releases/tag/2.0snap1-b4 )
