### ISSUE TITLE
there isn't an empty line between the "You reached the next layer" message and the message of unlocking the "Halfway there!" achievement

### ISSUE THREAD

**Issue by giganlak** [giganlak/wood#299]
![image](https://user-images.githubusercontent.com/79335163/185530373-3dfaa609-19be-445b-af02-e5057995f2fd.png)

**Comment by ConaII** [comment]
Issue fixed in [2.0snap1-b4]( https://github.com/giganlak/wood/releases/tag/2.0snap1-b4 )
