### ISSUE TITLE
if you do something but when you do that you find a traveling merchant, the message of the action that you did appears when you access the traveling merchant's menu instead of appearing after you leave

### ISSUE THREAD

**Issue by giganlak** [giganlak/wood#317]
![image](https://user-images.githubusercontent.com/79335163/188341039-8956885e-7baf-4536-9ba6-c20ac818e13d.png)

**Comment by ConaII** [comment]
Issue fixed in [2.0snap1-b4]( https://github.com/giganlak/wood/releases/tag/2.0snap1-b4 )
