### ISSUE TITLE
if you drink a poison flask and die, when you press a key to respawn, a message appears saying how many poison flasks you have left

### ISSUE THREAD

**Issue by giganlak** [giganlak/wood#318]
![image](https://user-images.githubusercontent.com/79335163/188341112-99a36dec-f37a-40ba-b09a-fde0271f73c8.png)

**Comment by ConaII** [comment]
Issue fixed in [2.0snap1-b4]( https://github.com/giganlak/wood/releases/tag/2.0snap1-b4 )
