### ISSUE TITLE
the game is falsely detected as a virus

### ISSUE THREAD

**Issue by giganlak** [giganlak/wood#347]
IT'S NOT, IT'S LITERALLY NOT A VIRUS

**Comment by ConaII** [comment]
**Program**
https://www.virustotal.com/gui/file/18f5c9567776ccfcae5ddf32a07fdeb8bef1e4fb3d4d7e7a0c9c9c0252da4ce7

**Launcher**
https://www.virustotal.com/gui/file/1ef9a19459636358b19e3a405a744e8999394687e8c9954f09167c96ab12f329
