### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by ConaII** [giganlak/wood#6]
Better UI / GUI
 - You should add more spaces
 - You could change "> " instead of ""
 - You could add used space and max space, ej: you open your back pack and it says 5/16, wood storage "30/100"
 - Clear function

**Comment by giganlak** [comment]
1. I don't know
2. Okay, i will add it on wood 1.16.1.1
3. maybe
4. no

**Comment by giganlak** [comment]
1. no
2. done
3. soon
4. no
